<?php

namespace ApiBundle\Repository;

/**
 * MedicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MedicationRepository extends \Doctrine\ORM\EntityRepository
{
}
