<?php

namespace ApiBundle\Repository;

/**
 * SmartPackageConfigurationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SmartPackageConfigurationRepository extends \Doctrine\ORM\EntityRepository
{
}
